# -*- mode: ruby -*-
 # vi: set ft=ruby :

 
# Require the AWS provider plugin
 require ‘vagrant-aws’

 
# Creating and configuring the AWS instance
 Vagrant.configure(‘2’) do |config|

 
# Use dummy AWS box
 config.vm.box = ‘aws’

 
# Specify configuration of AWS provider
 config.vm.provider ‘aws’ do |aws, override|
 # Read AWS authentication information from environment variables
 aws.access_key_id = ‘ABCR2NDJKZJIAJ5QVXGJK’
 aws.secret_access_key = ‘WAuZE39lKHXAJnCfbZf2y6DzRfeCsPUU/yZMRDWo’

 
# Specify SSH keypair to use
 aws.keypair_name = ‘vagrant’

 
# Specify region, AMI ID, Instance and security group
 aws.region = ‘ap-southeast-2’
 aws.ami = ‘ami-14b55f76’
 aws.instance_type = ‘t2.micro’
 aws.security_groups = [‘default’] 

# Specify username and private key path
 override.ssh.username = ‘ubuntu’
 override.ssh.private_key_path = ‘~/vagrant/vagrant’
 end
 end
